services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mass_spec_app:/mass_spec_app
    environment:
      - DB_HOST=database
      - DB_NAME=mass_spec_db
      - DB_USER=db_user
      - DB_PASS=zxcv0987


    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=mass_spec_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=zxcv0987
