services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mass_spec_web:/mass_spec_web
    environment:
      - DB_HOST=database
      - DB_NAME=spectrumdb
      - DB_USER=admin
      - DB_PASS=zxcv0987
      - DB_PORT=5432


    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=spectrumdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zxcv0987
      - POSTGRES_PORT=5432
